### ISSUE TITLE
Brutal Issue

### ISSUE THREAD

**Issue by Jtinha2000** [SmartlyDressedGames/Unturned-3.x-Community#3026]
**The server has been showing Fatal Errors, and we can't open our map or inventory, any suggestions on what it is?**

```
Caught fatal signal - signo:11 code:1 errno:0 addr:0x559e20cc7b90
Obtained 23 stack frames.
#0  0x007f3ca6581980 in funlockfile
#1  0x007f3ca565e561 in mono_set_break_policy
#2  0x007f3ca5648fa4 in _init
#3  0x007f3ca564aa1c in _init
#4  0x007f3ca564e712 in mono_print_method_from_ip
#5  0x in mono_print_thread_dump_from_ctx
#6  007f3ca56cef3f0x00000041930013 in (Unknown)
#7  0x00000040c51088 in SDG.Unturned.UseableConsumeable:performAid (SDG.Unturned.ItemConsumeableAsset)
#8  0x00000040bc8878 in SDG.Unturned.PlayerEquipment:simulate (uint,bool,bool,bool)
#9  0x000000403edcca in (wrapper runtime-invoke) object:runtime_invoke_voidthis (object,intptr,intptr,intptr)
#10 0x007f3ca564f7c5 in mono_print_method_from_ip
#11 0x007f3ca57bf390 in (Unknown)
#12 0x007f3ca57c023d in (Unknown)
#13 0x007f3ca7756502 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(gnu_cxx::normal_iterator<unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#14 0x007f3ca775489a in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(gnu_cxx::normal_iterator<unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#15 0x007f3ca773a6f7 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(gnu_cxx::normal_iterator<unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#16 0x007f3ca74dec8d in std::vector<float, std::allocator<float> >::_M_fill_insert(gnu_cxx::normal_iterator<float, std::vector<float, std::allocator<float> > >, unsigned long, float const&)
```

**Comment by SDGNelson** [comment]
From the callstack it looks like it is happening when a player uses a medical item on another player. It also looks like that Linux mono crash that started happening in 2019.4 LTS though (grr). Are you binding any of the consumeable aid events?
