### ISSUE TITLE
Crash on player connect

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#640]
Ubuntu 16.04
```
Connecting: PlayerID: 76561198858245741 Name: ℍReceiving unhandled NULL exception
#0  0x000000f5bc1b00 in (Unknown)
#1  0x000000ffc02a54 in strerror_l
#2  0x000000ffc02a60 in operator delete(void*)
#3  0x000000ffc02bc0 in operator delete(void*)
#4  0x000000ffc02be0 in operator delete(void*)
#5  0x000000ffc02c30 in (Unknown)
#6  0x000000ffc02c80 in (Unknown)
#7  0x000000ffc02ca0 in (Unknown)
#8  0x000000ffc02cd0 in (Unknown)
#9  0x000000ffc02d30 in (Unknown)
#10 0x000000ffc02d70 in (Unknown)
#11 0x000000ffc02d90 in (Unknown)
#12 0x000000ffc02db0 in (Unknown)
#13 0x000000ffc02de0 in (Unknown)
#14 0x000000ffc02e00 in (Unknown)
#15 0x000000ffc030b0 in (Unknown)
#16 0x000000ffc03200 in (Unknown)
#17 0x000000ffc03220 in (Unknown)
#18 0x000000ffc03390 in (Unknown)
#19 0x000000ffc033c0 in (Unknown)
#20 0x000000ffc03410 in (Unknown)
#21 0x000000ffc03480 in (Unknown)
#22 0x000000ffc034d0 in SteamAPI_SetTryCatchCallbacks
#23 0x000000ffc03500 in SteamAPI_SetTryCatchCallbacks
#24 0x000000ffc03550 in SteamAPI_SetTryCatchCallbacks
#25 0x000000ffc03580 in Steam_RunCallbacks
#26 0x000000ffc035b0 in SteamGameServer_RunCallbacks
#27 0x000000ffc035d0 in (Unknown)
#28 0x000000ffc03610 in (Unknown)
#29 0x000000ffc03620 in (Unknown)
#30 0x000000ffc03640 in (Unknown)
#31 0x000000ffc036b0 in (Unknown)
#32 0x000000ffc036f0 in mono_get_jit_info_from_method
#33 0x000000ffc03750 in mono_g_hash_table_print_stats
#34 0x000000ffc03790 in mono_runtime_invoke
#35 0x000000ffc03810 in operator delete(void*)
#36 0x000000ffc03830 in operator delete(void*)
#37 0x000000ffc03870 in operator delete(void*)
#38 0x000000ffc039a0 in operator delete(void*)
#39 0x000000ffc039e0 in operator delete(void*)
#40 0x000000ffc03a00 in operator delete(void*)
#41 0x000000ffc03a30 in zcfree
#42 0x000000ffc03f90 in __libc_start_main
#43 0x000000ffc04000 in zcfree
```
Seems to be the same reason as #620

**Comment by Th3God** [comment]
Do you still get it after .4 patch released today?

**Comment by educatalan02** [comment]
Since .4 Patch I've 24/24 using Ubuntu 16.04
