### ISSUE TITLE
[Nelson] Linux crash server [FIX 3.29.X.X]

### ISSUE THREAD

**Issue by strongunturned** [SmartlyDressedGames/Unturned-3.x-Community#644]
Hello! Nelson, in the last update we see problems with servers on the Ubuntu-16.04 platform. We have a big project, more than 200 servers are out of service, all servers are running on the Linux platform, respectively, all of our players and we do not know what to do.

Our mistakes:

An error occured while executing save []: System.NullReferenceException: Object reference not set
at SDG.Unturned.PlayerInventory.save () [0x000b0] in: 0
at SDG.Unturned.Player.save () [0x000c4] in: 0
at SDG.Unturned.SaveManager.save () [0x00047] in: 0
at SDG.Unturned.CommandSave.execute (Steamworks.CSteamID executorID, System.String parameter) [0x00000] in: 0
at SDG.Unturned.Command.check (Steamworks.CSteamID executorID, System.String method, System.String parameter) [0x0001b] in: 0
at Rocket.Unturned.Commands.UnturnedCommands + UnturnedVanillaCommand.Execute (Rocket.API.IRocketPlayer caller, System.String [] command) [0x0004c] in: 0
at Rocket.Core.Commands.RocketCommandManager + RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String [] command) [0x00000] in <42b9432d1ede4060ab7b64e73c43b05c>: 0
at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x00176] in <42b9432d1ede4060ab7b64e73c43b05c>: 0

The server simply crashes and it stops working and responding to the connection. There are other options, servers without mods work longer, but there are still crashes.

We ask you to answer, what should we expect, will there be a rollback of the version or a fix for this error?

Русский: 
Здравствуйте, уважаемый Нельсон, в последнем обновлении мы наблюдаем проблемы с сервером на платформе Ubuntu-16.04. У нас есть большой проект, более чем 200 серверов Unturned, все сервера работают на платформе Linux, соответсвенно все наши игроки и мы в целом, не знаем что делать. 

Наши ошибки: 

An error occured while executing save []: System.NullReferenceException: Object reference not set to an instance of an object 
at SDG.Unturned.PlayerInventory.save () [0x000b0] in :0 
at SDG.Unturned.Player.save () [0x000c4] in :0 
at SDG.Unturned.SaveManager.save () [0x00047] in :0 
at SDG.Unturned.CommandSave.execute (Steamworks.CSteamID executorID, System.String parameter) [0x00000] in ] in <42b9432d1ede4060ab7b64e73c43b05c>:0 
at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x00176] in <42b9432d1ede4060ab7b64e73c43b05c>:0 

Сервер просто крашит, и он прекрашает работать и реагировать на подключение. Есть и другие варианты, сервера без модов работают дольше, но все также есть краши. 

Мы просим Вас, ответить, чего нам стоит ожидать, будет ли откат версии или же фикс данной ошибки?    

[Rocket.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2923434/Rocket.log)
[unturned.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2923435/unturned.log)

**Comment by strongunturned** [comment]
[unturned.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2923409/unturned.log)
[Rocket.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2923412/Rocket.log)

**Comment by Trojaner** [comment]
The error you posted does not seem Linux specific or is not related to your crashes.
It basically says that save failed.

**Comment by strongunturned** [comment]
Trojaner, can watch unturned.log. 

Connecting: PlayerID: 76561198107455489 Name: Receiving unhandled NULL exception
#0  0x000000f779ca00 in (Unknown)
#1  0x000000ff939464 in strerror_l
#2  0x000000ff939470 in operator delete(void*)
#3  0x000000ff9395d0 in operator delete(void*)
#4  0x000000ff9395f0 in operator delete(void*)
#5  0x000000ff939640 in (Unknown)
#6  0x000000ff939690 in (Unknown)
#7  0x000000ff9396b0 in (Unknown)
#8  0x000000ff9396e0 in (Unknown)
#9  0x000000ff939740 in (Unknown)
#10 0x000000ff939780 in (Unknown)
#11 0x000000ff9397a0 in (Unknown)
#12 0x000000ff9397c0 in (Unknown)
#13 0x000000ff9397f0 in (Unknown)
#14 0x000000ff939810 in (Unknown)
#15 0x000000ff939ac0 in (Unknown)
#16 0x000000ff939c10 in (Unknown)
#17 0x000000ff939c30 in (Unknown)
#18 0x000000ff939da0 in (Unknown)
#19 0x000000ff939dd0 in (Unknown)
#20 0x000000ff939e20 in (Unknown)
#21 0x000000ff939e90 in (Unknown)
#22 0x000000ff939ee0 in SteamAPI_SetTryCatchCallbacks
#23 0x000000ff939f10 in SteamAPI_SetTryCatchCallbacks
#24 0x000000ff939f60 in SteamAPI_SetTryCatchCallbacks
#25 0x000000ff939f90 in Steam_RunCallbacks
#26 0x000000ff939fc0 in SteamGameServer_RunCallbacks
#27 0x000000ff939fe0 in (Unknown)
#28 0x000000ff93a020 in (Unknown)
#29 0x000000ff93a030 in (Unknown)
#30 0x000000ff93a050 in (Unknown)
#31 0x000000ff93a0c0 in (Unknown)
#32 0x000000ff93a100 in mono_get_jit_info_from_method
#33 0x000000ff93a160 in mono_g_hash_table_print_stats
#34 0x000000ff93a1a0 in mono_runtime_invoke
#35 0x000000ff93a220 in operator delete(void*)
#36 0x000000ff93a240 in operator delete(void*)
#37 0x000000ff93a280 in operator delete(void*)
#38 0x000000ff93a3b0 in operator delete(void*)
#39 0x000000ff93a3f0 in operator delete(void*)
#40 0x000000ff93a410 in operator delete(void*)
#41 0x000000ff93a440 in zcfree
#42 0x000000ff93a9a0 in __libc_start_main
#43 0x000000ff93aa10 in zcfree
An error occured while executing save []: System.NullReferenceException: Object reference not set to an instance of an object
  at SDG.Unturned.PlayerInventory.save () [0x000b0] in <fec4af2dacd8481fb47e018b7712907f>:0 
  at SDG.Unturned.Player.save () [0x000c4] in <fec4af2dacd8481fb47e018b7712907f>:0 
  at SDG.Unturned.SaveManager.save () [0x00047] in <fec4af2dacd8481fb47e018b7712907f>:0 
  at SDG.Unturned.CommandSave.execute (Steamworks.CSteamID executorID, System.String parameter) [0x00000] in <fec4af2dacd8481fb47e018b7712907f>:0 
  at SDG.Unturned.Command.check (Steamworks.CSteamID executorID, System.String method, System.String parameter) [0x0001b] in <fec4af2dacd8481fb47e018b7712907f>:0 
  at Rocket.Unturned.Commands.UnturnedCommands+UnturnedVanillaCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x0004c] in <efca55ac0a5949baae5c5de4a23818ac>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <42b9432d1ede4060ab7b64e73c43b05c>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x00176] in <42b9432d1ede4060ab7b64e73c43b05c>:0

**Comment by Trojaner** [comment]
Yes the native stacktrace is a Linux crash bug but it was reported already.

**Comment by strongunturned** [comment]
Trojaner, We need a developer’s response, as the above stated that we have a large number of servers (+200 servers), transfer them to Windows or wait for a fix from Nelson

**Comment by Ascivv1** [comment]
200 plus servers huh? When I type Strong in the server Internet box with all of the any filters set to any, only 4 servers popped up.

**Comment by strongunturned** [comment]
Ascivv1, Where did you see that we are talking about Storng servers? We are talking about our other projects in the field of Unturned

**Comment by Ascivv1** [comment]
There is nothing talking about the STRONG servers, just wanted to point that out. As Trojaner said, it is a save issue. The native stracktrace thing can be found in threads #611 and #612

**Comment by strongunturned** [comment]
Nelson, what should we expect, will there be a fix or will the version be rolled back?

**Comment by SDGNelson** [comment]
Will re-open for the moment to see if we hear back from other hosts as well

Sorry that it took me a while to decide how to proceed. Wasn't able to do it programatically so for the moment it requires restarting the Unity editor for separate builds

**Comment by strongunturned** [comment]
@SDGNelson, Thank you very much! Everything works fine, problems with crash and mono are no longer observable. Thanks Nelson! Sorry for the flood and further success!

**Comment by strongunturned** [comment]
@SDGNelson, The server crashes again, there are no errors, but the plugins do not work and crashes are observed
